#!/bin/bash

# Yocto ADT Installer
#
# Copyright 2010-2011 by Intel Corp.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy 
# of this software and associated documentation files (the "Software"), to deal 
# in the Software without restriction, including without limitation the rights 
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
# copies of the Software, and to permit persons to whom the Software is 
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
# THE SOFTWARE.

config_file="adt_installer.conf"
source `pwd`/$config_file

LOCAL_OPKG_LOC="opkg/build/opkg"
LOCAL_OPKG_FOLDER="opkg/build"

# List all supported root fs types and target types,
# it will be used in user configuration validity checking
YOCTOADT_SUPPORTED_ROOTFS="-neon -vfp -32"
YOCTOADT_SUPPORTED_TARGETS="armv5e armv7a cortexa5 i586 core2"
# Different host (32 bit or 64 bit) will have different opkg
# configuration files
YOCTOADT_OPKG_CONF_FILE_32="opkg/conf/opkg-sdk-i686.conf"
YOCTOADT_OPKG_CONF_FILE_64="opkg/conf/opkg-sdk-x86_64.conf"
SDK_VENDOR=-emacsdk
DEFAULT_INSTALL_FOLDER=/opt/emac/$SDK_VERSION
