#!/bin/sh
#
# Starts UutServer
#

PIDFILE=/var/run/UutServer.pid
UUTSERVER_BIN=/usr/bin/uut_server

[ -x $UUTSERVER_BIN ] || exit 0

start() {
	echo -n "Starting UUT-Server: "
	umask 077
	start-stop-daemon -S -q -b -m -p $PIDFILE \
		--exec $UUTSERVER_BIN
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping UUT-Server: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && { echo "OK"; rm -f $PIDFILE; } || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit 0
