variables:
  GIT_MACHINE: "none"
  GIT_CLEAN_FLAGS: none
  INCLUDE_SDK: "false"

include:
  - local: "ci/gitlab/build.yml"
  - local: "ci/gitlab/arm-machines.yml"
  - local: "ci/gitlab/arm64-machines.yml"
  - local: "ci/gitlab/x86-machines.yml"
  - local: "ci/gitlab/x86_64-machines.yml"

stages:
  - build

emac-image-manual: # allow this if to be skipped
  extends: .kas-build
  variables:
    KAS_DISTROS_FILE: "kas/distros/emac.yml:"
    KAS_MACHINES_FILE: "kas/machines/arm/ipac9x25.yml:"
  rules:
    - if: $GIT_MACHINE == "none"
  when: manual
  allow_failure: true
