.initenv-script: &initenv-script
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd repo-tool
  - ./init-build.sh -c
  - ./init-build.sh -g "$REPO_TOOL_GROUPS"
  - cat ${CI_PROJECT_DIR}/conf/bblayers.conf.sample $LAYERS_SAMPLE > ${CI_PROJECT_DIR}/repo-tool/build/conf/bblayers.conf
  - source setup_env.sh
  - export

.create-links-for-deploy: &create-links-for-deploy
  - test -e ${CI_PROJECT_DIR}/deploy && unlink ${CI_PROJECT_DIR}/deploy; 
  - ln -sf /srv/emac-oe/deploy/$EMAC_CLIENT_NAME/$EMAC_IMAGE/$MACHINE ${CI_PROJECT_DIR}/deploy

.start-bb-after-close: &start-bb-after-close
  - cd repo-tool
  - source start_afterclose.sh

.default-no-fetch-manual: &default-no-fetch-manual
  variables:
    GIT_STRATEGY: none
  tags:
    - oe-builder
    - bitbake
  when: manual
  allow_failure: true

variables:
  MACHINE: "none"
  REPO_TOOL_GROUPS: 'default'
  LAYERS_SAMPLE: '${CI_PROJECT_DIR}/conf/machine/${MACHINE}/${MACHINE}.bblayers.conf.sample'
  EMAC_CLIENT_NAME: 'emac'
  EMAC_IMAGE: 'emac-image'
  BB_NUMBER_THREADS: "20"
  PARALLEL_MAKE: "-j 12"
  GIT_CLEAN_FLAGS: none
  
stages:
  - setup
  - build
  - test
  - deploy

init-env:
  stage: setup
  variables:
    GIT_STRATEGY: fetch
  when: manual
  allow_failure: true
  tags:
    - oe-builder
    - bitbake
  script:
    - *initenv-script

clean-bitbake-locks:
  stage: setup
  <<: *default-no-fetch-manual
  script:
    - pushd repo-tool/build
    - rm bitbake.*

clean-recipe:
  stage: setup
  <<: *default-no-fetch-manual
  script:
    - test ! -z $RECIPE_NAME
    - *start-bb-after-close
    - bitbake $RECIPE_NAME -c clean

clean-recipe-sstate:
  stage: setup
  <<: *default-no-fetch-manual
  script:
    - test ! -z $RECIPE_NAME
    - *start-bb-after-close
    - bitbake $RECIPE_NAME -c cleansstate

clean-image:
  stage: setup
  extends: clean-recipe
  variables:
    RECIPE_NAME: $EMAC_IMAGE

clean-image-sstate:
  stage: setup
  extends: clean-recipe-sstate
  variables:
    RECIPE_NAME: $EMAC_IMAGE

.build-recipe:
  variables:
    GIT_STRATEGY: none
    BITBAKE_CMD: 'bitbake'
    RECIPE_NAME: $EMAC_IMAGE
  tags:
    - oe-builder
    - bitbake
  timeout: 6hr
  script:
    - *initenv-script
    - $BITBAKE_CMD $RECIPE_NAME
    - *create-links-for-deploy

build-emac-image:
  stage: build
  extends: .build-recipe
  rules:
  - if: '$MACHINE != "none"'
  artifacts:
    paths:
      - deploy/image/

build-emac-image-sdk:
  stage: build
  extends: .build-recipe
  when: manual
  allow_failure: true
  variables:
    BITBAKE_CMD: 'bitbake -c do_populate_sdk'
  artifacts:
    paths:
      - deploy/sdk/

.build-standard-qemu:
  <<: *default-no-fetch-manual
  script:
    - *start-bb-after-close
    - echo $BITBAKE_CMD
    - $BITBAKE_CMD
    - test -e ${CI_PROJECT_DIR}/deploy && unlink ${CI_PROJECT_DIR}/deploy; 
    - ln -sf /srv/emac-oe/deploy/$EMAC_CLIENT_NAME/$EMAC_IMAGE/$QEMU_MACHINE ${CI_PROJECT_DIR}/deploy
  artifacts:
    paths:
      - deploy/image/

build-emac-image-qemu-arm:
  stage: build
  extends: .build-standard-qemu
  variables:
    EMAC_IMAGE: 'emac-image'
    BITBAKE_CMD: bitbake mc:qemu-armv7:$EMAC_IMAGE
    QEMU_MACHINE: qemuarm

build-emac-image-qemu-x86:
  stage: build
  extends: .build-standard-qemu
  variables:
    EMAC_IMAGE: 'emac-image'
    BITBAKE_CMD: bitbake mc:qemu-x86-64:$EMAC_IMAGE
    QEMU_MACHINE: qemux86-64

test-image:
  stage: test
  variables:
    GIT_STRATEGY: none
  tags:
    - oe-builder
    - bitbake
  rules:
    - if: '$MACHINE != "none"'
  script:
    - echo "Nothing to do here. Yet"

deploy-image:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - oe-builder
    - bitbake
  rules:
    - if: '$MACHINE != "none"'
  script:
    - echo "Nothing to do here Yet"

