variables:
  GIT_MACHINE: "none"
  DISTRO_CODENAME: "duncan"
  REPO_TOOL_GROUPS: "default"
  LAYERS_SAMPLE: "${CI_PROJECT_DIR}/conf/machine/${MACHINE}/${MACHINE}.bblayers.conf.sample"
  EMAC_CLIENT_NAME: "emac"
  EMAC_IMAGE: "emac-image"
  BB_NUMBER_THREADS: "20"
  PARALLEL_MAKE: "-j 12"
  GIT_CLEAN_FLAGS: none
  INCLUDE_SDK: "false"
  INCLUDE_QEMU: "false"
  INCLUDE_DEBUG: "false"
  OE_DEPLOYMENT: "false"

stages:
  - debug
  - build
  - test
  - deploy

emac-image-manual:
  extends: .build-emac-image
  variables:
    MACHINE: ipac9x25
  rules:
    - if: $GIT_MACHINE == "none"
  when: manual
  allow_failure: true

include:
  - local: "conf/gitlab-ci/base-build-machine.yml"
  - local: "conf/gitlab-ci/build-qemu.yml"
    rules:
      - if: $INCLUDE_QEMU == "true"
  - local: "conf/gitlab-ci/debugging-jobs.yml"
    rules:
      - if: $INCLUDE_DEBUG == "true"
  - local: "conf/machine/hmi-043t/hmi-043t.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'hmi-043t'
  - local: "conf/machine/intel-x86/intel-x86.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'intel-x86'
  - local: "conf/machine/ipac9x25/ipac9x25.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'ipac9x25'
  - local: "conf/machine/jetson-agx-xavier-devkit/jetson-agx-xavier-devkit.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'jetson-agx-xavier-devkit'
  - local: "conf/machine/ppc-150t/ppc-150t.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'ppc-150t'
  - local: "conf/machine/som9g25/som9g25.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'som9g25'
  - local: "conf/machine/som9g45/som9g45.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'som9g45'
  - local: "conf/machine/som9x25/som9x25.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'som9x25'
  - local: "conf/machine/som3354/som3354.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'som3354'
  - local: "conf/machine/som3517/som3517.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'som3517'
  - local: "conf/machine/soma5d36/soma5d36.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'soma5d36'
  - local: "conf/machine/soma5d36mp/soma5d36mp.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'soma5d36mp'
  - local: "conf/machine/somimx6/somimx6.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'somimx6'
  - local: "conf/machine/somimx6q-ha/somimx6q-ha.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'somimx6q-ha'
  - local: "conf/machine/somimx6ul/somimx6ul.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'somimx6ul'
  - local: "conf/machine/vortex-sbc/vortex-sbc.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'vortex-sbc'
  - local: "conf/machine/vox-150/vox-150.yml"
    rules:
      - if: $GIT_MACHINE == 'all' || $GIT_MACHINE == 'vox-150'
