variables:
  GIT_MACHINE: "none"
  DISTRO_CODENAME: "spike"
  GIT_CLEAN_FLAGS: none
  INCLUDE_SDK: "false"

include:
  - local: "kas/gitlab-ci/basic.yml"
  - local: "kas/gitlab-ci/arm-machines.yml"
  - local: "kas/gitlab-ci/x86-machines.yml"

stages:
  - build
  - clean

emac-image-manual: # allow this if to be skipped
  extends: .kas-build
  variables:
    KAS_MACHINE: ipac9x25
  rules:
    - if: $GIT_MACHINE == "none"
  when: manual
  allow_failure: true
