stages:
  - build

build-image:
  stage: build
  tags:
    - Joseph_builder
  script:
    - whoami;
    - cd /home/jmills/git/5.4_imx_qt5;
    - source start_afterclose.sh;
    - cd /home/jmills/git/5.4_imx_qt5/build_5.4_jmills;
    - pwd;
    - bitbake-layers show-recipes;
