#!/bin/sh

if [ ! -d /home/root ]; then
    echo "Creating /home/root "
    mkdir -p /home/root
fi

echo "Running init-partition"
if [ -x /usr/sbin/fbset ]; 
then
    fbresH=$(fbset | grep geometry | cut -d " " -f6)
    fbresV=$(fbset | grep geometry | cut -d " " -f7)
fi

[ -e /etc/init.d/dbus-1 ] && echo "Running D-Bus init" && /etc/init.d/dbus-1 start
[ -x /usr/bin/oe_info.sh ] && /usr/bin/oe_info.sh
