build-ipac9x25:
  extends: .kas-build
  variables:
    KAS_MACHINE: ipac9x25
  rules:
    - if: $GIT_MACHINE == "ipac9x25" || $GIT_MACHINE == "all"

build-som9g25:
  extends: .kas-build
  variables:
    KAS_MACHINE: som9g25
  rules:
    - if: $GIT_MACHINE == "som9g25" || $GIT_MACHINE == "all"

build-som9g45:
  extends: .kas-build
  variables:
    KAS_MACHINE: som9g45
  rules:
    - if: $GIT_MACHINE == "som9g45" || $GIT_MACHINE == "all"

build-som9x25:
  extends: .kas-build
  variables:
    KAS_MACHINE: som9x25
  rules:
    - if: $GIT_MACHINE == "som9x25" || $GIT_MACHINE == "all"

build-som3354:
  extends: .kas-build
  variables:
    KAS_MACHINE: som3354
  rules:
    - if: $GIT_MACHINE == "som3354" || $GIT_MACHINE == "all"

build-som3517:
  extends: .kas-build
  variables:
    KAS_MACHINE: som3517
  rules:
    - if: $GIT_MACHINE == "som3517" || $GIT_MACHINE == "all"

build-soma5d36:
  extends: .kas-build
  variables:
    KAS_MACHINE: soma5d36
  rules:
    - if: $GIT_MACHINE == "soma5d36" || $GIT_MACHINE == "all"

build-soma5d36mp:
  extends: .kas-build
  variables:
    KAS_MACHINE: soma5d36mp
  rules:
    - if: $GIT_MACHINE == "soma5d36mp" || $GIT_MACHINE == "all"

build-somimx6:
  extends: .kas-build
  variables:
    KAS_MACHINE: somimx6
  rules:
    - if: $GIT_MACHINE == "somimx6" || $GIT_MACHINE == "all"

build-somimx6q-ha:
  extends: .kas-build
  variables:
    KAS_MACHINE: somimx6q-ha
  rules:
    - if: $GIT_MACHINE == "somimx6q-ha" || $GIT_MACHINE == "all"

build-somimx6ul:
  extends: .kas-build
  variables:
    KAS_MACHINE: somimx6ul
  rules:
    - if: $GIT_MACHINE == "somimx6ul" || $GIT_MACHINE == "all"