build-somimx6:
  extends: .kas-build
  variables:
    KAS_MACHINE: somimx6
  rules:
    - if: $GIT_MACHINE == "somimx6" || $GIT_MACHINE == "nxp" || $GIT_MACHINE == "all"

build-somimx6ul:
  extends: .kas-build
  variables:
    KAS_MACHINE: somimx6ul
  rules:
    - if: $GIT_MACHINE == "somimx6ul" || $GIT_MACHINE == "nxp" || $GIT_MACHINE == "all"
