build-som3354:
  extends: .kas-build
  variables:
    KAS_MACHINE: som3354
  rules:
    - if: $GIT_MACHINE == "som3354" || $GIT_MACHINE == "ti" || $GIT_MACHINE == "all"

build-som3517:
  extends: .kas-build
  variables:
    KAS_MACHINE: som3517
  rules:
    - if: $GIT_MACHINE == "som3517" || $GIT_MACHINE == "ti" || $GIT_MACHINE == "all"
