build-genericx86:
  extends: .kas-build
  variables:
    KAS_MACHINES_FILE: genericx86.yml
  rules:
    - if: $GIT_MACHINE == "genericx86" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-genericx86-i586:
  extends: .kas-build
  variables:
    KAS_MACHINES_FILE: genericx86-i586.yml
  rules:
    - if: $GIT_MACHINE == "genericx86-i586" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-genericx86-64:
  extends: .kas-build
  variables:
    KAS_MACHINES_FILE: genericx86-64.yml
  rules:
    - if: $GIT_MACHINE == "genericx86-64" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-intel-core2-32:
  extends: .kas-build
  variables:
    KAS_MACHINES_FILE: intel-core2-32.yml
  rules:
    - if: $GIT_MACHINE == "intel-core2-32" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-intel-corei7-64:
  extends: .kas-build
  variables:
    KAS_MACHINES_FILE: intel-corei7-64.yml
  rules:
    - if: $GIT_MACHINE == "intel-corei7-64" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"