build-genericx86:
  extends: .kas-build
  variables:
    KAS_DISTROS_FILE: "kas/distros/emac.yml:"
    KAS_MACHINES_FILE: "kas/machines/x86/genericx86.yml:"
  rules:
    - if: $GIT_MACHINE == "genericx86" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-genericx86-i586:
  extends: .kas-build
  variables:
    KAS_DISTROS_FILE: "kas/distros/emac.yml:"
    KAS_MACHINES_FILE: "kas/machines/x86/genericx86-i586.yml:"
  rules:
    - if: $GIT_MACHINE == "genericx86-i586" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"

build-intel-core2-32:
  extends: .kas-build
  variables:
    KAS_DISTROS_FILE: "kas/distros/emac.yml:"
    KAS_MACHINES_FILE: "kas/machines/x86/intel-core2-32.yml:"
  rules:
    - if: $GIT_MACHINE == "intel-core2-32" || $GIT_MACHINE == "x86" || $GIT_MACHINE == "all"