header:
  version: 12
  includes:
    - kas/repos/upstream/poky.yml

defaults:
  repos:
    refspec: kirkstone

env:
  CI_REPOSITORY_URL: "Not built via Gitlab CI/CD"
  CI_COMMIT_BRANCH: "Not built via Gitlab CI/CD"
  
local_conf_header:
  base: |
    CONF_VERSION = "2"
    BB_SERVER_TIMEOUT = "30"
    BB_DISKMON_DIRS ??= "\
      STOPTASKS,${TMPDIR},1G,100K \
      STOPTASKS,${DL_DIR},1G,100K \
      STOPTASKS,${SSTATE_DIR},1G,100K \
      STOPTASKS,/tmp,100M,100K \
      HALT,${TMPDIR},100M,1K \
      HALT,${DL_DIR},100M,1K \
      HALT,${SSTATE_DIR},100M,1K \
      HALT,/tmp,10M,1K"

  setup: |
    BUILDHISTORY_COMMIT = "1"
    INHERIT += " rm_work buildhistory image-buildinfo"
    OE_TERMINAL = "auto"
    PATCHRESOLVE = "noop"

  packaging: PACKAGE_CLASSES ?= "package_ipk package_deb package_rpm"
    
  base_extra_build_info: |
    IMAGE_BUILDINFO_VARS:append = " CI_REPOSITORY_URL CI_COMMIT_BRANCH CLIENT_NAME "

  sshkeys: |
    CORE_IMAGE_EXTRA_INSTALL += "ssh-pregen-hostkeys"

  sdk: |
    SDKMACHINE ?= "x86_64"
