TI33X_CFLAGS           = -DLINUX=1 -DEGL_API_FB=1
QMAKE_LIBS_EGL         += -lEGL
QMAKE_LIBS_OPENGL_ES2  += -lGLESv2 -lEGL -lGAL

QMAKE_CFLAGS           += $$TI33X_CFLAGS
QMAKE_CXXFLAGS         += $$TI33X_CFLAGS

QMAKE_PLATFORM         += linux
QT_QPA_DEFAULT_PLATFORM = eglfs

