.initenv-script: &initenv-script
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - cd repo-tool
  - ./init-build.sh -c
  - ./init-build.sh -g "$REPO_TOOL_GROUPS"
  - cat ${CI_PROJECT_DIR}/conf/bblayers.conf.sample $LAYERS_SAMPLE > ${CI_PROJECT_DIR}/repo-tool/build/${DISTRO_CODENAME}/conf/bblayers.conf
  - |
    export BB_ENV_PASSTHROUGH_ADDITIONS="$BB_ENV_PASSTHROUGH_ADDITIONS \
      EMAC_CLIENT_NAME \
      EMAC_IMAGE \
      EMAC_DISPLAY_HW \
      EMAC_DISPLAY \
      EMAC_SHELLMANAGER \
      EMAC_INITMANAGER \
      EMAC_NETWORKMANAGER \
      EMAC_AUDIOMANAGER \
      EMAC_PACKAGEMANAGER"
  - source setup_env.sh
  - env | uniq | sort

.build-recipe:
  variables:
    GIT_STRATEGY: fetch
    BITBAKE_CMD: 'bitbake'
    RECIPE_NAME: $EMAC_IMAGE
  tags:
    - oebuilder
    - bitbake
  timeout: 6hr
  script:
    - *initenv-script
    - $BITBAKE_CMD $RECIPE_NAME

.build-emac-image:
  stage: build
  variables:
    GIT_STRATEGY: fetch
    BITBAKE_CMD: 'bitbake'
    RECIPE_NAME: $EMAC_IMAGE
  tags:
    - oebuilder
    - bitbake
  timeout: 6hr
  script:
    - *initenv-script
    - $BITBAKE_CMD $RECIPE_NAME
    - test "$INCLUDE_SDK" == "true" && $BITBAKE_CMD -c do_populate_sdk $RECIPE_NAME
    - $BITBAKE_CMD package-index
    - upload_oe


