#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
  menuentry "EMAC OE PPC-057T" {
	savedefault
	set root=(hd0,msdos1)
	linux16 /boot/bzImage root=/dev/sda1 console=ttyS0,115200 vga=786 quiet splash ro rootfstype=ext4 noapic
}
