#!/bin/sh
VGA=""
[ ! -z $GRUB_GFXMODE ] && VGA="vga=$GRUB_GFXMODE"
bootstring="root=$GRUB_DEVICE console=$GRUB_SERIAL_COMMAND $VGA $GRUB_CMDLINE_LINUX_DEFAULT $GRUB_CMDLINE_LINUX"
cat <<EOF
  menuentry "EMAC OE" {
        set root=(hd0,msdos1)
        linux16 /boot/bzImage $bootstring
}
EOF
