#!/bin/bash
export red="\033[0;31m"
export green="\033[0;32m"
export blue="\033[0;34m"
export cyan="\033[0;36m"
export white="\033[0;37m"
export b_red="\033[1;31m"
export b_green="\033[1;32m"
export b_blue="\033[1;34m"
export b_cyan="\033[1;36m"
export b_white="\033[1;37m"
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s checkwinsize
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

case "$TERM" in
xterm*|rxvt*)
    PS1="\[$b_blue\]\$(date \"+%H:%M:%S\") \[$b_blue\][\[$b_white\]\w\[$b_blue\]]\[$b_green\] \u\[$b_white\] $\[$white\] "
    ;;
screen)
    PS1="\[$b_blue\]\$(date \"+%H:%M:%S\") \[$b_blue\][\[$b_white\]\w\[$b_blue\]]\[$b_green\] \u\[$b_white\] $\[$white\] "
    ;;    
*)
    PS1="\[$b_blue\]\$(date \"+%H:%M:%S\") \[$b_blue\][\[$b_white\]\w\[$b_blue\]]\[$b_green\] \u\[$b_white\] $\[$white\] "
    ;;
esac



# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'


if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

