#!/bin/sh

echo "Running init-partition"
if [ ! -d /home/root ]; then
    echo "Creating /home/root "
    mkdir -p /home/root
    if [ -x /etc/enlightenment/e.tar.gz ]; then
        echo "Extracting enlightenment defaults"
        tar zxf /etc/enlightenment/e.tar.gz -C /home/root/
    fi
    if [ -x /etc/emac/demos/graphics_ppm.tar.gz ]; then
        echo "Extracting graphics demos"
        mkdir -p /home/root/Demos/graphics
        tar zxf /etc/emac/demos/graphics_ppm.tar.gz -C /home/root/Demos/graphics
        rm /etc/emac/demos/graphics_ppm.tar.gz
    fi
    if [ -x /etc/emac/demos/audio_demos.tar.gz ]; then
        echo "Extracting audio demos"
        mkdir -p /home/root/Demos/audio
        tar zxf /etc/emac/demos/audio_demos.tar.gz -C /home/root/Demos/audio
        rm /etc/emac/demos/audio_demos.tar.gz
    fi
    rm -rf /etc/emac/demos
fi

[ -e /etc/init.d/dbus-1 ] && echo "Running D-Bus init" && /etc/init.d/dbus-1 start

[ -x /usr/bin/oe_info.sh ] && /usr/bin/oe_info.sh
